export const LIST_TIME_EVENTS_REQUEST = 'LIST_TIME_EVENTS_REQUEST';
export const LIST_TIME_EVENTS_SUCCESS = 'LIST_TIME_EVENTS_SUCCESS';

export const CREATE_TIME_EVENTS_REQUEST = 'CREATE_TIME_EVENTS_REQUEST';
export const CREATE_TIME_EVENTS_SUCCESS = 'CREATE_TIME_EVENTS_SUCCESS';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';