export const LIST_TIME_EVENTS_REQUEST = 'LIST_TIME_EVENTS_REQUEST';
export const LIST_TIME_EVENTS_SUCCESS = 'LIST_TIME_EVENTS_SUCCESS';
export const LIST_TIME_EVENTS_FAILED = 'LIST_TIME_EVENTS_FAILED';